insightrails/config/routes.rb
Rails.application.routes.draw do
  resources :insights
  resources :ideas
  resources :patterns
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

insightrails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

insightrails/app/models/idea.rb
class Idea < ApplicationRecord
end

insightrails/app/models/insight.rb
class Insight < ApplicationRecord
end

insightrails/app/models/pattern.rb
class Pattern < ApplicationRecord
end

insightrails/app/models/user.rb
class User < ApplicationRecord
end

insightrails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

insightrails/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:insight_id, :pattern_id, :text, :user_id)
    end
end

insightrails/app/controllers/insights_controller.rb
class InsightsController < ApplicationController
  before_action :set_insight, only: [:show, :edit, :update, :destroy]

  # GET /insights
  # GET /insights.json
  def index
    @insights = Insight.all
  end

  # GET /insights/1
  # GET /insights/1.json
  def show
  end

  # GET /insights/new
  def new
    @insight = Insight.new
  end

  # GET /insights/1/edit
  def edit
  end

  # POST /insights
  # POST /insights.json
  def create
    @insight = Insight.new(insight_params)

    respond_to do |format|
      if @insight.save
        format.html { redirect_to @insight, notice: 'Insight was successfully created.' }
        format.json { render :show, status: :created, location: @insight }
      else
        format.html { render :new }
        format.json { render json: @insight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insights/1
  # PATCH/PUT /insights/1.json
  def update
    respond_to do |format|
      if @insight.update(insight_params)
        format.html { redirect_to @insight, notice: 'Insight was successfully updated.' }
        format.json { render :show, status: :ok, location: @insight }
      else
        format.html { render :edit }
        format.json { render json: @insight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insights/1
  # DELETE /insights/1.json
  def destroy
    @insight.destroy
    respond_to do |format|
      format.html { redirect_to insights_url, notice: 'Insight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insight
      @insight = Insight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insight_params
      params.require(:insight).permit(:user_id, :text)
    end
end

insightrails/app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :set_pattern, only: [:show, :edit, :update, :destroy]

  # GET /patterns
  # GET /patterns.json
  def index
    @patterns = Pattern.all
  end

  # GET /patterns/1
  # GET /patterns/1.json
  def show
  end

  # GET /patterns/new
  def new
    @pattern = Pattern.new
  end

  # GET /patterns/1/edit
  def edit
  end

  # POST /patterns
  # POST /patterns.json
  def create
    @pattern = Pattern.new(pattern_params)

    respond_to do |format|
      if @pattern.save
        format.html { redirect_to @pattern, notice: 'Pattern was successfully created.' }
        format.json { render :show, status: :created, location: @pattern }
      else
        format.html { render :new }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patterns/1
  # PATCH/PUT /patterns/1.json
  def update
    respond_to do |format|
      if @pattern.update(pattern_params)
        format.html { redirect_to @pattern, notice: 'Pattern was successfully updated.' }
        format.json { render :show, status: :ok, location: @pattern }
      else
        format.html { render :edit }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patterns/1
  # DELETE /patterns/1.json
  def destroy
    @pattern.destroy
    respond_to do |format|
      format.html { redirect_to patterns_url, notice: 'Pattern was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pattern
      @pattern = Pattern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pattern_params
      params.require(:pattern).permit(:text, :user_id)
    end
end

insightrails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

insightrails/app/helpers/application_helper.rb
module ApplicationHelper
end

insightrails/app/helpers/ideas_helper.rb
module IdeasHelper
end

insightrails/app/helpers/insights_helper.rb
module InsightsHelper
end

insightrails/app/helpers/patterns_helper.rb
module PatternsHelper
end

insightrails/app/helpers/users_helper.rb
module UsersHelper
end

insightrails/app/views/ideas/_form.html.erb
<%= form_for(idea) do |f| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :insight_id %>
    <%= f.number_field :insight_id %>
  </div>

  <div class="field">
    <%= f.label :pattern_id %>
    <%= f.number_field :pattern_id %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

insightrails/app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

insightrails/app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Insight</th>
      <th>Pattern</th>
      <th>Text</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.insight_id %></td>
        <td><%= idea.pattern_id %></td>
        <td><%= idea.text %></td>
        <td><%= idea.user_id %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

insightrails/app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

insightrails/app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Insight:</strong>
  <%= @idea.insight_id %>
</p>

<p>
  <strong>Pattern:</strong>
  <%= @idea.pattern_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @idea.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @idea.user_id %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

insightrails/app/views/insights/_form.html.erb
<%= form_for(insight) do |f| %>
  <% if insight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(insight.errors.count, "error") %> prohibited this insight from being saved:</h2>

      <ul>
      <% insight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

insightrails/app/views/insights/edit.html.erb
<h1>Editing Insight</h1>

<%= render 'form', insight: @insight %>

<%= link_to 'Show', @insight %> |
<%= link_to 'Back', insights_path %>

insightrails/app/views/insights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Insights</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insights.each do |insight| %>
      <tr>
        <td><%= insight.user_id %></td>
        <td><%= insight.text %></td>
        <td><%= link_to 'Show', insight %></td>
        <td><%= link_to 'Edit', edit_insight_path(insight) %></td>
        <td><%= link_to 'Destroy', insight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insight', new_insight_path %>

insightrails/app/views/insights/new.html.erb
<h1>New Insight</h1>

<%= render 'form', insight: @insight %>

<%= link_to 'Back', insights_path %>

insightrails/app/views/insights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @insight.user_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @insight.text %>
</p>

<%= link_to 'Edit', edit_insight_path(@insight) %> |
<%= link_to 'Back', insights_path %>

insightrails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Insightrails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

insightrails/app/views/patterns/_form.html.erb
<%= form_for(pattern) do |f| %>
  <% if pattern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pattern.errors.count, "error") %> prohibited this pattern from being saved:</h2>

      <ul>
      <% pattern.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

insightrails/app/views/patterns/edit.html.erb
<h1>Editing Pattern</h1>

<%= render 'form', pattern: @pattern %>

<%= link_to 'Show', @pattern %> |
<%= link_to 'Back', patterns_path %>

insightrails/app/views/patterns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patterns</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patterns.each do |pattern| %>
      <tr>
        <td><%= pattern.text %></td>
        <td><%= pattern.user_id %></td>
        <td><%= link_to 'Show', pattern %></td>
        <td><%= link_to 'Edit', edit_pattern_path(pattern) %></td>
        <td><%= link_to 'Destroy', pattern, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pattern', new_pattern_path %>

insightrails/app/views/patterns/new.html.erb
<h1>New Pattern</h1>

<%= render 'form', pattern: @pattern %>

<%= link_to 'Back', patterns_path %>

insightrails/app/views/patterns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @pattern.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @pattern.user_id %>
</p>

<%= link_to 'Edit', edit_pattern_path(@pattern) %> |
<%= link_to 'Back', patterns_path %>

insightrails/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

insightrails/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

insightrails/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

insightrails/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

insightrails/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>